### ISSUE TITLE
Bump the forked version of the operator to the latest v0.4.1

### ISSUE THREAD

**Issue by ptesny** [kyma-incubator/sap-btp-service-operator#32]
Please, bump the forked version of the operator to the latest v0.4.1 as it contains critical fixes and improvements with helm deployments.

PS.
The version currently deployed to the latest kyma release 2.12.1 is still v0.3.6

<img width="812" alt="image" src="https://user-images.githubusercontent.com/52403733/230025152-4882ba95-da37-406b-afc6-9862d2822e55.png">

**Comment by szwedm** [comment]
PR with update to the latest version:
https://github.com/kyma-incubator/sap-btp-service-operator/pull/33
We will create a release after PR is merged.

**Comment by szwedm** [comment]
Forked btp-operator v0.4.2 has been released. Closing.
